defmodule Demo.Repo.Migrations.AddOnDeleteCascade do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:storage_attachments, "storage_attachments_page_id_fkey"))

    drop(constraint(:storage_attachments, "storage_attachments_post_id_fkey"))

    alter table(:storage_attachments) do
      modify(
        :post_id,
        references(:posts,
          column: :id,
          name: "storage_attachments_post_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )

      modify(
        :page_id,
        references(:pages,
          column: :id,
          name: "storage_attachments_page_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end
  end

  def down do
    drop(constraint(:storage_attachments, "storage_attachments_post_id_fkey"))

    drop(constraint(:storage_attachments, "storage_attachments_page_id_fkey"))

    alter table(:storage_attachments) do
      modify(
        :page_id,
        references(:pages,
          column: :id,
          name: "storage_attachments_page_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :post_id,
        references(:posts,
          column: :id,
          name: "storage_attachments_post_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end
end
